### ISSUE TITLE
How can i fix this error

### ISSUE THREAD

**Issue by bexoda** [justadudewhohacks/face-api.js#387] opened 2019-08-15 19:12 UTC
face-api.min.js:1 Uncaught (in promise) Error: Failed to link vertex and fragment shaders.
    at Wr (face-api.min.js:1)
    at t.createProgram (face-api.min.js:1)
    at face-api.min.js:1
    at face-api.min.js:1
    at t.getAndSaveBinary (face-api.min.js:1)
    at t.compileAndRun (face-api.min.js:1)
    at t.conv2dWithIm2Row (face-api.min.js:1)
    at t.conv2d (face-api.min.js:1)
    at Zt.engine.runKernel.x (face-api.min.js:1)
    at face-api.min.js:1
Wr @ face-api.min.js:1
t.createProgram @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
t.getAndSaveBinary @ face-api.min.js:1
t.compileAndRun @ face-api.min.js:1
t.conv2dWithIm2Row @ face-api.min.js:1
t.conv2d @ face-api.min.js:1
Zt.engine.runKernel.x @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
t.scopedRun @ face-api.min.js:1
t.runKernel @ face-api.min.js:1
conv2d_ @ face-api.min.js:1
conv2d @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
t.scopedRun @ face-api.min.js:1
t.tidy @ face-api.min.js:1
t.tidy @ face-api.min.js:1
Kh @ face-api.min.js:1
r.runMobilenet @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
t.scopedRun @ face-api.min.js:1
t.tidy @ face-api.min.js:1
t.tidy @ face-api.min.js:1
r.forwardInput @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
n @ face-api.min.js:1
Promise.then (async)
o @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
e.runAndExtendWithFaceDetections @ face-api.min.js:1
e.withFaceLandmarks @ face-api.min.js:1
(anonymous) @ script.js:24
face-api.min.js:1 C:\fakepath(179,2-41): warning X3550: array reference cannot be used as an l-value; not natively addressable, forcing loop to unroll
C:\fakepath(179,2-41): error X3500: array reference cannot be used as an l-value; not natively addressable
C:\fakepath(158,7-60): error X3511: forced to unroll loop, but unrolling failed.
C:\fakepath(156,7-60): error X3511: forced to unroll loop, but unrolling failed.

Warning: D3D shader compilation failed with default flags. (ps_3_0)
 Retrying with avoid flow control
C:\fakepath(179,2-41): error X3500: array reference cannot be used as an l-value; not natively addressable
C:\fakepath(158,7-60): error X3511: forced to unroll loop, but unrolling failed.
C:\fakepath(156,7-60): error X3511: forced to unroll loop, but unrolling failed.

Warning: D3D shader compilation failed with avoid flow control flags. (ps_3_0)
 Retrying with prefer flow control
C:\fakepath(179,2-41): warning X3550: array reference cannot be used as an l-value; not natively addressable, forcing loop to unroll
C:\fakepath(179,2-41): error X3500: array reference cannot be used as an l-value; not natively addressable
C:\fakepath(158,7-60): error X3511: forced to unroll loop, but unrolling failed.
C:\fakepath(156,7-60): error X3511: forced to unroll loop, but unrolling failed.

Warning: D3D shader compilation failed with prefer flow control flags. (ps_3_0)

Failed to create D3D Shaders

how can i fix this issue

**Comment by justadudewhohacks** [comment] 2019-09-13 08:53
Duplicate of #327

**Closed by justadudewhohacks** 2019-09-13 08:53 UTC
Labels: duplicate
